ckm/basicapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicapp import views
from django.conf import settings
from django.conf.urls.static import static
app_name='basicapp'

urlpatterns=[
    url(r'^$',views.Baseview.as_view(),name='home_view'),
    url(r'explore/$',views.ExploresListView.as_view(),name='explores_list_view'),
    url(r'explore/(?P<pk>[-\w]+)$',views.ExploresDetailView.as_view(),name='explore_detail'),
    url(r'hotels/$',views.HotelsListView.as_view(),name='hotels_list_view'),
    url(r'hotels/(?P<pk>[-\w]+)$',views.HotelsDetailView.as_view(),name='hotel_detail'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ckm/ckm/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('basicapp.urls')),
    
]

ckm/basicapp/models.py
from django.db import models

# Create your models here.
class Explores(models.Model):
    name=models.TextField(max_length=180)
    short_desc=models.TextField(max_length=None)
    desc=models.TextField(max_length=None)
    google_map_html=models.TextField(max_length=None,blank=True)
    google_map_link=models.TextField(max_length=None,blank=True)
    dist_from_bang=models.TextField(max_length=None,blank=True)
    dist_from_mys=models.TextField(max_length=None,blank=True)
    dist_from_ckm=models.TextField(max_length=None,blank=True)
    thumbnail=models.ImageField(upload_to='explores',blank=True)
    facebook_link_thumbnail=models.TextField(max_length=None,blank=True)
    rank=models.PositiveIntegerField()
    three_view=models.TextField(max_length=None,blank=True)
    image_1=models.ImageField(upload_to='explores',blank=True)
    image_2=models.ImageField(upload_to='explores',blank=True)
    image_3=models.ImageField(upload_to='explores',blank=True)
    image_4=models.ImageField(upload_to='explores',blank=True)
    image_5=models.ImageField(upload_to='explores',blank=True)
    image_6=models.ImageField(upload_to='explores',blank=True)
    image_7=models.ImageField(upload_to='explores',blank=True)
    image_8=models.ImageField(upload_to='explores',blank=True)
    image_9=models.ImageField(upload_to='explores',blank=True)
    image_10=models.ImageField(upload_to='explores',blank=True)

    def __str__(self):
        return str(self.rank)+":"+self.name





class Hotels(models.Model):
    name=models.TextField(max_length=None)
    desc=models.TextField(max_length=None,blank=False)
    google_link=models.TextField(max_length=None,blank=False)
    thumbnail=models.ImageField(max_length=None,blank=False)

    google_map_html=models.TextField(max_length=None,blank=False)
    rank=models.PositiveIntegerField()
    google_rating=models.TextField(max_length=15)
    veg=models.BooleanField()

    def __str__(self):
        return self.name

ckm/basicapp/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from basicapp.models import Explores,Hotels
app_name='basicapp'

# Create your views here.
class Baseview(TemplateView):
    template_name='html/basicapp/home_page.html'

class ExploresListView(ListView):
    model=Explores
    def get_queryset(self):
        return Explores.objects.all().order_by('rank')

class ExploresDetailView(DetailView):
    context_object_name='place_detail'
    model=Explores
    template_name='basicapp/explores_detail.html'


class HotelsListView(ListView):
    context_object_name='hotel_list'
    model=Hotels
    def get_queryset(self):
         return Hotels.objects.all().order_by('rank')


class HotelsDetailView(DetailView):
    context_object_name='hotel'
    model=Hotels
    template_name='basicapp/hotels_detail.html'

ckm/templates/basicapp/explores_detail.html
{%extends 'html/base.html'%}
{%load static%}


{%block body_block%}
<div class="box">

  <h1 style="text-align:center;">{{place_detail.name}}</h1>
  <div  class="card 2">
    <div class="card_image">
      <img style="width:80vw;" src="{{place_detail.thumbnail.url}}" alt="">

     </div>

  </div>
  <h5 style="padding:20px;">{{place_detail.desc}}</h5>
  <h5 style="padding:20px;">{{place_detail.short_desc}}</h5>
  <div class="side">
    <div style="padding:20px;margin:20px;margin-bottom:20vw;" id="map">
      <div style="width:100%;height:350px" class="d-md-none d-sm-block  mb-3">
  <iframe style="align:center;margin:40px;" src="{{place_detail.google_map_html}}" width="100%" height="225vw" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  <a style="text-align:center;" href="{{place_detail.google_map_link}}" class="style-1">Go to Google Map</a>
</div>
<div style="width:100%;height:450px;text-align:center;" class="d-none d-md-block cus  mb-3">
  <div  class="container">
    <iframe class="container" src="{{place_detail.google_map_html}}" width="900" height="600vw" frameborder="0" style="align:center;padding-left:5vw;;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    <a href="{{place_detail.google_map_link}}" class="style-1">Go to Google Map</a>

  </div>



</div>


    </div>


  </div>
  <div style="text-align:center;" class="dist">
<h5> Distance from chikmagalur:{{place_detail.dist_from_ckm}}</h5>
<h5>Distance from Bangalore:{{place_detail.dist_from_bang}}</h5>
<h5>Distance from Mysore:{{place_detail.dist_from_mys}}</h5>
  </div>
  <div style="text-align:center;color:white;" class="container">
    <iframe src="{{place_detail.three_view}}" width="500" height="420" style="" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>

  </div>
  <div class="alll">

    <div id="leftie">
      <a href="{% url 'basicapp:explores_list_view'%}" class="style-1">Back</a>
    </div>

    <div id="rightie">
      <a href="{% url 'basicapp:home_view'%}" class="style-1"> Go to home page</a>

    </div>

  </div>


</div>




<style media="screen">
.box{
  margin:40px;
  padding:10px;
  margin-bottom:20vw;
  border-radius: 10px;
  box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
}
.cards-list {
z-index: 0;
width: 100%;
display: flex;
justify-content: space-around;
flex-wrap: wrap;
}

.card {
margin: 30px auto;
width: 80vw;
height: inherit;
border-radius: 10px;
box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
cursor: pointer;
background-color: black;
transition: 0.4s;
}

.card .card_image {
width: inherit;
height: inherit;
border-radius: 10px;
}

.card .card_image img {
width: inherit;
height: inherit;
border-radius: 10px;
object-fit: cover;
}

.card .card_title {
text-align: center;
border-radius: 0px 0px 40px 40px;

font-weight: bold;
font-size: 30px;
margin-top: -80px;
height: 40px;
}

.card:hover {
transform: scale(0.9, 0.9);
box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
-5px -5px 30px 15px rgba(0,0,0,0.22);
}

.style-1 {
  border:3px solid white;
  color:white;

  text-transform:uppercase;
  padding:10px;
  font-weight:600;
  max-width:250px;
  display:block;
  text-align:center;
  margin:10px auto;
  position:relative;
}
.style-1:hover {
  background:#000;
  border-color:white;
  color:#fff;
}
.cus{
  width: 100%;
}
.alll{
  width:100%;
  padding:20px;
}
#leftie{
  float:left;
}
#rightie{
  float:right;
}
</style>

{%endblock%}

ckm/templates/basicapp/explores_list.html
{%extends 'html/base.html'%}
{%load static%}

{%block body_block%}
<h1 style="text-align:center;padding-top:6vw;">The places you can explore in chikmagalur</h1>
{% for place in explores_list%}
<div class="box">
  <h1>{{place.rank}}: {{place.name}}</h1>
  <div  class="card 2">
    <div class="card_image">
      <img style="width:80vw;" src="{{place.thumbnail.url}}" alt="">

     </div>

  </div>

  <h5>{{place.short_desc}}</h5>

  <h4 style="padding-top:20px;">Distance:</h4>
  <h5>Distance from Bangalore:{{place.dist_from_bang}}</h5>
  <h5>Distance from Mysore:{{place.dist_from_mys}}</h5>
  <h5>Distance from chikmagalur:{{place.dist_from_ckm}}</h5>
<div style="padding-bottom:18vw;" class="loop">
  <div id="left">

  <a href="{{place.google_map_link}}"><img style="width:8vw;height:8vw;"   src="{%static 'icons/google__map_icon.png'%}" alt="not found"></a>


  </div>
  <div id="right">
   <a href="{{place.id}}" class="style-1">Read More</a>

  </div>


</div>
</div>








{%endfor%}




<style media="screen">

  .box{
    margin:40px;
    border-radius: 10px;
    box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
  }
  .cards-list {
z-index: 0;
width: 100%;
display: flex;
justify-content: space-around;
flex-wrap: wrap;
}

.card {
margin: 30px auto;
width: 80vw;
height: inherit;
border-radius: 10px;
box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
cursor: pointer;
background-color: black;
transition: 0.4s;
}

.card .card_image {
width: inherit;
height: inherit;
border-radius: 10px;
}

.card .card_image img {
width: inherit;
height: inherit;
border-radius: 10px;
object-fit: cover;
}

.card .card_title {
text-align: center;
border-radius: 0px 0px 40px 40px;

font-weight: bold;
font-size: 30px;
margin-top: -80px;
height: 40px;
}

.card:hover {
transform: scale(0.9, 0.9);
box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
-5px -5px 30px 15px rgba(0,0,0,0.22);
}

.title-white {
color: white;
}

.title-black {
color: black;
}

@media all and (max-width: 500px) {
.card-list {
/* On small screens, we are no longer using row direction but column */
flex-direction: column;
}
}

.loop{
  width:100%;

}
#left{
  float:left;
  border-radius: 10px;
  transition: 0.4s;
}
#left:hover {
transform: scale(0.9, 0.9);
box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
-5px -5px 30px 15px rgba(0,0,0,0.22);
}
#right{
  float:right;
}
.style-1 {
  border:3px solid white;
  color:white;

  text-transform:uppercase;
  padding:10px;
  font-weight:600;
  max-width:250px;
  display:block;
  text-align:center;
  margin:10px auto;
  position:relative;
}
.style-1:hover {
  background:#000;
  border-color:white;
  color:#fff;
}
</style>
{% endblock %}

ckm/templates/basicapp/hotels_list.html
{%extends 'html/base.html'%}
{%load static%}

{% block body_block%}
<h1 style="padding:6vw;text-align:center;">Chikmagaluru offers unique variety of hotesl ranging from sophisticated cafes to traditional south indian hotels</h1>
{% for hotel in hotel_list%}
<div class="box">
  <h1>{{hotel.rank}} : {{hotel.name}}  {% if hotel.veg%}<img style="width:4vw;height:4vw;" src="{%static 'icons/veg.jpg'%}" alt="">{%else%}<img style="width:4vw;height:4vw;" src="{%static 'icons/non_veg.png'%}" alt="">{%endif%}
</h1>
  <div  class="card 2">
    <div class="card_image">
      <img style="width:60vw;height:40vw;" src="{{hotel.thumbnail.url}}" alt="">

     </div>

  </div>
  <h5>{{hotel.desc}}</h5>

  <div style="padding-bottom:18vw;" class="loop">
    <div id="left">

  <a href="{{hotel.google_link}}" class="style-1">{{hotel.google_rating}} <span class="fa fa-star checked"></span></a>

    </div>
    <div id="right">
     <a href="{{hotel.id}}" class="style-1">Read More</a>


    </div>


  </div>




  {%endfor%}

</div>





<style media="screen">
.box{
  margin:40px;
  border-radius: 10px;
  box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
}
.cards-list {
z-index: 0;
width: 100%;
display: flex;
justify-content: space-around;
flex-wrap: wrap;
}

.card {
margin: 30px auto;
width: 60vw;
height: inherit;
border-radius: 10px;
box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
cursor: pointer;
background-color: black;
transition: 0.4s;
}

.card .card_image {
width: inherit;
height: inherit;
border-radius: 10px;
}

.card .card_image img {
width: inherit;
height: inherit;
border-radius: 10px;
object-fit: cover;
}

.card .card_title {
text-align: center;
border-radius: 0px 0px 40px 40px;

font-weight: bold;
font-size: 30px;
margin-top: -80px;
height: 40px;
}

.card:hover {
transform: scale(0.9, 0.9);
box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
-5px -5px 30px 15px rgba(0,0,0,0.22);
}

.title-white {
color: white;
}

.title-black {
color: black;
}

@media all and (max-width: 500px) {
.card-list {
/* On small screens, we are no longer using row direction but column */
flex-direction: column;
}
}
.loop{
  width:100%;

}
#left{
  float:left;
  border-radius: 10px;
  transition: 0.4s;
}
#left:hover {
transform: scale(0.9, 0.9);
box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
-5px -5px 30px 15px rgba(0,0,0,0.22);
}
#right{
  float:right;
}
.style-1 {
  border:3px solid white;
  color:white;

  text-transform:uppercase;
  padding:10px;
  font-weight:600;
  max-width:250px;
  display:block;
  text-align:center;
  margin:10px auto;
  position:relative;
}
.style-1:hover {
  background:#000;
  border-color:white;
  color:#fff;
}
</style>
{%endblock%}

ckm/templates/html/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <!-- bootstrap link -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- google font link -->
<link href="https://fonts.googleapis.com/css?family=Gotu&display=swap" rel="stylesheet">

<!-- custom link -->
  <link rel="stylesheet" href="{%static 'css/base.css'%}">
  <link href="https://fonts.googleapis.com/css2?family=MuseoModerno&display=swap" rel="stylesheet">



    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: transparent!important;">
      <a style="color:white;" class="navbar-brand bigbrand" href="{%url 'basicapp:home_view'%}">CKM</a>
      <button style="border-color:white;" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a style="margin-left:50px;color:white;" class="nav-link" href="{% url 'basicapp:explores_list_view'%}">Explore places</a>
              </li>
              <li class="nav-item active">
                <a style="margin-left:50px;color:white;" class="nav-link" href="{% url 'basicapp:hotels_list_view'%}">Hotels and Cafe</a>
              </li>
              <li class="nav-item active">
                <a style="margin-left:50px;color:white;" class="nav-link" href="www.netflix.com">Homestays</a>
              </li>
              <li class="nav-item active">
                <a style="margin-left:50px;color:white;" class="nav-link" href="www.netflix.com">Malnad Specials</a>
              </li>

            </ul>

          <a href="#" style="color:white;">Contact Us</a>
          </div>
</nav>
    {%block body_block%}

    {%endblock%}

    <div  class="footer">
      <div style="    border-radius: 10px;
        box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(255,255,255,0.22);" class="footer-content">
        <div style="padding-top:20px;padding-left:20px;" id="left1">
          <p>About</p>
          <p>The main aim of our page is to help you discover the beauty of nature in chikmagalur.Help you have a hassle free trip by organising your trips.Make the world see the beauty of malnad culture </p>
        </div>
        <div style="padding-top:20px;" id="left2">
          <p><a href="https://www.facebook.com/Chikkamagalure/"<i class="fa fa-facebook" style="font-size:36px;color:white;padding-right:10px;"></i> </a> Like us on facebook</p>
          <p ><a href="https://www.instagram.com/chikamagalur_theland_of_hills/?igshid=1d9eqz8jdliq4"<i class="fa fa-instagram" style="font-size:36px;color:white;padding-right:10px;"></i> </a> Follow us on Instagam</p>
          <p><a href="https://www.youtube.com/channel/UChefcw3OEZqNxxLcaUzu73Q"<i class="fa fa-youtube" style="font-size:36px;color:white;padding-right:10px;"></i> </a> Subscribe our channel on Youtube</p>
          <p><a href="https://twitter.com/Chikkamagaluru1?s=09"<i class="fa fa-twitter" style="font-size:36px;color:white;padding-right:10px;"></i> </a> Follow us on twitter</p>

        </div>
        <div id="right">



        </div>
        <h4>Contact Us</h4>
        <p><i class="fa fa-phone" style="font-size:36px;color:white;padding-right:10px;"></i> +91-8277062747</p>
        <p><i class="fa fa-phone" style="font-size:36px;color:white;padding-right:10px;"></i> +91-6362755594</p>
        <h4>Mail us :</h4>
        <p><a href="https://mail.google.com/"<i class="fa fa-envelope" style="font-size:24px;color:white;padding:0px;margin:0px;width:30px;height:25px;padding-right:10px;"></i></a>chikkamagaluruthelandofhills@gmail.com</p>




      </div>


    </div>
    <p> </p>
    <p> </p>
    <p> </p>
    <p><p style="padding-left:40%;padding-right:40%;text-align:center;" >< > with<i style="font-size:20px;" class="fa fa-heart "></i>by Ckm and team</p></p>






    <style media="screen">
      body{
        background-image: linear-gradient(to right,#181818,rgb(20,20,20));
        font-family: 'MuseoModerno', cursive;
        color:white;
      }
      .footer-content{
        width:100%;
        padding: 40px;

      }
      #left1{
        width:36%;
        padding:10px;
        padding-right:15px;
        margin: 10px;
        float:left;
      }
      #left2{
        width: 36%;
        padding: 10px;
        float: left;
      }
      #right{
        width: 24%;
      }

      #right{

        padding:10px;
        float: right;
      }
    </style>


  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

ckm/templates/html/basicapp/home_page.html
{%extends 'html/base.html'%}
{%load static%}


{%block body_block%}
<section id="home_">
  <div style="background-image:url({%static 'images/home_1.jpg'%})"   class="welcome text-dark" >
    <p >CHIKMAGALURU<p>
    <h2 style="font-size:4vw;color:white;">The land of hills!</h2>
    <h2 style="color:white;">Escape the ordinary, explore the divinity of nature in the coffee land </h3>
  </div>

</section>

<div class="container">
  <p style="color:white;font-size:x-large;padding-top:10px;padding-bottom:12px;text-align:center;">Explore various attractions and the beauty of nature here</p>

</div>



<div class="cards-list">



  <div class="card 1">
  <div class="card_image">
    <a href="#"><img style="width:300px;height:400px;" src="{% static 'images/homestay.jpg'%}" /></a>

    </div>
  <div class="card_title title-white">
    <p>Homestays</p>
  </div>
</div>
<div  class="card 2">
  <div class="card_image">
    <a href="{%url 'basicapp:explores_list_view'%}"><img  style="width:300px;height:400px;" src="{% static 'images/mulla.jpg'%}" /></a>
   </div>
  <div class="card_title title-white">
    <p>Explore places</p>
  </div>
</div>

<div class="card 3">
  <div class="card_image">
    <a href="{% url 'basicapp:hotels_list_view'%}"><img style="width:300px;height:400px;" src="{% static 'images/coffee.jpg' %}" /></a>

  </div>
  <div class="card_title">
    <p>Cafe and hotels</p>
  </div>
</div>

  <div class="card 4">
  <div class="card_image">
    <a href="#"><img style="width:300px;height:400px;" src="{% static 'images/attractions.jfif'%}" /></a>

    </div>
  <div class="card_title title-white">
    <p>Malnad Specials</p>
  </div>
  </div>

</div>



<div class="jumbotron">
  <div class="container">
    <h1 style="text-align:center;" class="display-4">What do we offer?</h1>
    <p id="middle"  class="lead">The info about all the places in chikmagalur can be found </p>
    <p id="middle" class="lead">The unique aspects that chikmagalur has to offer,in finding the hidden places that only few know about</p>
    <p id="middle" class="lead">The restaurant recomendations,hotel bookings,the homestay bookings</p>
    <p id="middle" class="lead">We help you in booking of your trip</p>
  </div>
  <p style="text-align:center;" ><a href="https://www.facebook.com/Chikkamagalure/"<i id="fb" class="fa fa-facebook" style="font-size:36px;color:white;padding-right:10px;margin:20px;"></i> </a>  <a href="https://www.instagram.com/chikamagalur_theland_of_hills/?igshid=1d9eqz8jdliq4"<i id="in" class="fa fa-instagram" style="font-size:34px;color:white;"></i> </a>  <a href="https://www.youtube.com/channel/UChefcw3OEZqNxxLcaUzu73Q"<i id="yt" class="fa fa-youtube" style="font-size:36px;color:white;padding-right:10px;margin:20px;"></i> </a> <a id="tw" href="https://twitter.com/Chikkamagaluru1?s=09"<i class="fa fa-twitter" style="font-size:36px;color:white;padding-right:10px;margin:0px;"></i> </a></p>
</div>









<style media="screen">

.welcome{
            padding:15% 2%;
              width:100%;
              height:fill;
              padding-left:middle;
              text-align: center;
              color:black;
              background-size: cover;
          }
.welcome p{
  font-size:10vw;
  color:black;
}


          .cards-list {
      z-index: 0;
      width: 100%;
      display: flex;
      justify-content: space-around;
      flex-wrap: wrap;
    }

    .card {
      margin: 30px auto;
      width: 300px;
      height: 400px;
      border-radius: 10px;
    box-shadow: 5px 5px 30px 7px rgba(0,0,0,0.25), -5px -5px 30px 7px rgba(0,0,0,0.22);
      cursor: pointer;
      background-color: black;
      transition: 0.4s;
    }

    .card .card_image {
      width: inherit;
      height: inherit;
      border-radius: 10px;
    }

    .card .card_image img {
      width: inherit;
      height: inherit;
      border-radius: 10px;
      object-fit: cover;
    }

    .card .card_title {
      text-align: center;
      border-radius: 0px 0px 40px 40px;

      font-weight: bold;
      font-size: 30px;
      margin-top: -80px;
      height: 40px;
    }

    .card:hover {
      transform: scale(0.9, 0.9);
      box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
        -5px -5px 30px 15px rgba(0,0,0,0.22);
    }

    .title-white {
      color: white;
    }

    .title-black {
      color: black;
    }

    @media all and (max-width: 500px) {
      .card-list {
        /* On small screens, we are no longer using row direction but column */
        flex-direction: column;
      }
    }

    .offer{


      padding:15% 2%;
        width:100%;
        height:fill;
        padding-left:middle;
        text-align: center;
        color:black;
        background-size: cover;
        box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
          -5px -5px 30px 15px rgba(0,0,0,0.22);
          background-color: #393E46;
    }
    .box{
      box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
        -5px -5px 30px 15px rgba(0,0,0,0.22);
        margin:25px;


    }
    .jumbotron{
    background-image: url({%static 'images/down.jpg'%});
    content: fill;
      margin:40px;
      box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
        -5px -5px 30px 15px rgba(0,0,0,0.72);
          border-radius: 10px;

    }
.jumbotron .container p{
  text-align: center;
}
.fa {

  font-size: 30px;
  width: 50px;
  height:50px;
  padding:10px;
  text-align: center;
  text-decoration: none;
  border-radius: 50%;
}
.faa:hover {
    opacity: 0.7;
}
#fb{
  background: #3B5998;
  color: white;
}
#tw {
  background: #55ACEE;
  color: white;
}
#yt {
  background: #bb0000;
  color: white;
}
#in {
  background: #125688;
  color: white;
}





</style>

{%endblock%}